config:
  send_anonymous_usage_stats: false

dbt_synapse:
  target: synapse
  outputs:
    synapse:
      type: synapse
      driver: 'ODBC Driver 18 for SQL Server'
      server: "{{ env_var('DBT_SYNAPSE_SERVER') }}.sql.azuresynapse.net"
      port: 1433
      database: "{{ env_var('DBT_SYNAPSE_DATABASE') }}"
      schema: stg
      user: "{{ env_var('DBT_SYNAPSE_USER') }}"
      password: "{{ env_var('DBT_SYNAPSE_PASSWORD') }}"
